### ISSUE TITLE
Specs docker-compose sur PostgreSQL/PostGIS

### ISSUE THREAD

**Issue by rmaziere** [fab-geocommuns/RNB-coeur#381]
Il y a deux paramètres : platform et shm_size qui semblent inutiles.
```yml
  db:
    image: postgis/postgis:16-master
    platform: linux/amd64
    shm_size: 1gb
```

**platform**
https://github.com/fab-geocommuns/RNB-coeur/blob/c18da62771ca25419da13ff01fd4ab0d8b44ce88/docker-compose.yml#L27
permet de spécifier l'architecture sur laquelle on souhaite déployer le conteneur, mais à partir du moment-où nous déployons sur notre/nos serveurs, l'utilité est faible.

**shm_size**
https://github.com/fab-geocommuns/RNB-coeur/blob/c18da62771ca25419da13ff01fd4ab0d8b44ce88/docker-compose.yml#L28
permet de spécifier la limite de mémoire pour le build d'une image, mais postgis est déjà buildé.
